meta:
  version: 3
  flow: Classic

DESIGN_NAME: ir_recorder_replay_chip_top
USE_SLANG: true

VERILOG_FILES:
  - dir::../../IRRecorder_Replay/Types_PKG/src/ir_types_pkg.sv
  - dir::../../IRDecoder/EdgeDetector/src/edge_detector.sv
  - dir::../../IRDecoder/PulseTimer/src/pulse_timer.sv
  - dir::../../IRDecoder/NECDecoder/src/nec_decoder.sv
  - dir::../../IRDecoder/OutputFormatter/src/output_formatter.sv
  - dir::../../IRDecoder/UART_TX/src/uart_tx.sv
  - dir::../../IRRecorder_Replay/Recorder/src/ir_recorder.sv
  - dir::../../IRRecorder_Replay/STORAGE_BRAM/src/ir_storage_bram.sv
  - dir::../../IRRecorder_Replay/Replay_FSM/src/ir_replay_fsm.sv
  - dir::../../IRRecorder_Replay/nec_encoder/src/nec_encoder.sv
  - dir::../../IRRecorder_Replay/TX/src/ir_tx.sv
  - dir::ir_recorder_replay_top.sv
  - dir::ir_recorder_replay_chip_top.sv

CLOCK_PORT: clk
CLOCK_PERIOD: 100

FP_SIZING: relative
FP_CORE_UTIL: 30

PL_TARGET_DENSITY_PCT: 40
GPL_CELL_PADDING: 2

VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]