// Auto-generated by LibreLane
module ir_recorder_replay_chip_top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input ir_in,
  input record_req,
  input replay_req,
  input[2:0] slot_sel,
  output ir_tx_npn_drive,
  output uart_tx,
  output ld7,
  output ld6,
  output ld5,
  output ld4,
  output ld3,
  output ld2,
  output ld1,
  output ld0,
  output rec_done,
  output rep_done,
  output busy,
  output error
);
endmodule
